# Generated by Django 3.2.19 on 2024-08-12 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dashbord', '0001_initial'),
        ('ouvrage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisOuvrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(blank=True, max_length=200, null=True)),
                ('ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouvrage.affaireouvrage')),
                ('redacteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RapportVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('order_in_affaire', models.IntegerField()),
                ('objet', models.CharField(blank=True, max_length=500)),
                ('statut', models.CharField(choices=[(0, 'En cours'), (1, 'Accepté'), (2, 'Classé'), (3, 'Diffuse')], default=0, max_length=10)),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashbord.affaire')),
            ],
        ),
        migrations.CreateModel(
            name='CommentaireAvisOuvrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asuivre', models.BooleanField(default=False)),
                ('commentaire', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('lever', models.BooleanField(default=False)),
                ('avis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapport_visite.avisouvrage')),
            ],
        ),
        migrations.AddField(
            model_name='avisouvrage',
            name='rv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapport_visite.rapportvisite'),
        ),
    ]
