# Generated by Django 3.2.19 on 2024-08-31 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('En cours', 'En cours'), ('Achevé', 'Achevé'), ('Abandonné', 'Abandonné')], default='En cours', max_length=20)),
                ('numero_offre', models.IntegerField(blank=True, null=True)),
                ('numero_contrat', models.CharField(default='', max_length=100)),
                ('libelle_contrat', models.CharField(blank=True, default='', max_length=100)),
                ('date_contrat', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BatimentPlanAffaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Chantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PlanAffaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('risque', models.CharField(choices=[('Normal', 'Normal'), ('Particulier', 'Particulier'), ('Complexe', 'Complexe')], max_length=20)),
                ('libelle_planAffaire', models.CharField(blank=True, max_length=50, null=True)),
                ('devise', models.CharField(choices=[('$', '$'), ('€', '€')], max_length=10)),
                ('type', models.CharField(choices=[('CTC', 'CTC'), ('VT', 'VT')], max_length=10)),
                ('type_montant', models.CharField(choices=[('HT', 'HT'), ('TTC', 'TTC')], default='HT', max_length=10)),
                ('prix', models.IntegerField(blank=True, null=True)),
                ('debut_prestation', models.DateField(blank=True, null=True)),
                ('debut_chantier', models.DateField(blank=True, null=True)),
                ('fin_chantier', models.DateField(blank=True, null=True)),
                ('visite', models.IntegerField(blank=True, null=True)),
                ('doc', models.IntegerField(blank=True, null=True)),
                ('rapport_initiaux', models.IntegerField(blank=True, default=0, null=True)),
                ('synthese', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('fiche_transfert', models.FileField(blank=True, null=True, upload_to='')),
                ('point_risque_virgilence_associe', models.TextField(blank=True, null=True)),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashbord.affaire')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_produit', models.CharField(max_length=3)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_affaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorals', to='Dashbord.planaffaire')),
                ('tutored', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntrepriseAffaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashbord.affaire')),
            ],
        ),
    ]
