# Generated by Django 3.2.19 on 2024-08-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affaire',
            name='statut',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Achevé', 'Achevé'), ('Abandonné', 'Abandonné')], default='En cours', max_length=20),
        ),
    ]
