# Generated by Django 3.2.19 on 2024-08-19 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0003_alter_affaire_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatimentPlanAffaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batiment', models.ManyToManyField(to='Dashbord.Batiment')),
                ('plan_affaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashbord.planaffaire')),
            ],
        ),
    ]
