# Generated by Django 3.2.19 on 2024-07-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0029_entrepriseaffaire_unique_entreprise_affaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planaffaire',
            old_name='libelle',
            new_name='libelle_planAffaire',
        ),
        migrations.AlterField(
            model_name='affaire',
            name='statut',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Achevé', 'Achevé'), ('Abandonné', 'Abandonné')], default='En cours', max_length=20),
        ),
        migrations.AlterField(
            model_name='planaffaire',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
