# Generated by Django 3.2.19 on 2024-08-11 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashbord', '0031_tutorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='plan_affaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorals', to='Dashbord.planaffaire'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutored',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorals', to=settings.AUTH_USER_MODEL),
        ),
    ]
