# Generated by Django 3.2.19 on 2024-08-13 07:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commentaire', '0001_initial'),
        ('rapport_visite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RICT', '0002_initial'),
        ('Dashbord', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyntheseAvis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.date.today)),
                ('statut', models.IntegerField(choices=[(0, 'En cours'), (1, 'Accepté'), (2, 'Classé'), (3, 'Diffuse')], default=0)),
                ('order', models.IntegerField(default=0)),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashbord.affaire')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SyntheseCommentaireDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commentaire.commentaire')),
                ('synthese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthese.syntheseavis')),
            ],
        ),
        migrations.CreateModel(
            name='SyntheseCommentaireArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RICT.commentaireavisarticle')),
                ('synthese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthese.syntheseavis')),
            ],
        ),
        migrations.CreateModel(
            name='SyntheseComentaireRV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapport_visite.commentaireavisouvrage')),
                ('synthese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthese.syntheseavis')),
            ],
        ),
        migrations.AddConstraint(
            model_name='synthesecommentairedocument',
            constraint=models.UniqueConstraint(fields=('synthese', 'commentaire'), name='unique_synthese_commentaire_document'),
        ),
        migrations.AddConstraint(
            model_name='synthesecommentairearticle',
            constraint=models.UniqueConstraint(fields=('synthese', 'commentaire'), name='unique_synthese_commentaire_article'),
        ),
        migrations.AddConstraint(
            model_name='synthesecomentairerv',
            constraint=models.UniqueConstraint(fields=('synthese', 'commentaire'), name='unique_synthese_commentaire_rv'),
        ),
    ]
