# Generated by Django 3.2.19 on 2024-08-13 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dashbord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codification', models.CharField(choices=[('F', 'F'), ('RMQ', 'RMQ'), ('HM', 'HM'), ('SO', 'SO'), ('IM', 'IM')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='CommentaireAvisArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.CharField(max_length=200)),
                ('a_suivre', models.BooleanField(default=True)),
                ('lever', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DescriptionSommaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Disposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MissionRICT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RICT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('statut', models.CharField(choices=[(0, 'En cours'), (1, 'Accepté'), (2, 'Classé'), (3, 'Diffuse')], default=0, max_length=10)),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashbord.affaire')),
            ],
        ),
    ]
