# Generated by Django 3.2.19 on 2024-08-13 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mission', '0001_initial'),
        ('RICT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionrict',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.missionactive'),
        ),
        migrations.AddField(
            model_name='missionrict',
            name='rict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RICT.rict'),
        ),
        migrations.AddField(
            model_name='disposition',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.articlemission'),
        ),
        migrations.AddField(
            model_name='disposition',
            name='rict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RICT.rict'),
        ),
        migrations.AddField(
            model_name='descriptionsommaire',
            name='rict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RICT.rict'),
        ),
        migrations.AddField(
            model_name='commentaireavisarticle',
            name='id_avis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RICT.avisarticle'),
        ),
        migrations.AddField(
            model_name='avisarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.articlemission'),
        ),
        migrations.AddField(
            model_name='avisarticle',
            name='rict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RICT.rict'),
        ),
        migrations.AddConstraint(
            model_name='disposition',
            constraint=models.UniqueConstraint(fields=('rict', 'article'), name='unique_rict_article'),
        ),
    ]
