# Generated by Django 3.2.19 on 2024-08-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cplt_geo', models.CharField(blank=True, max_length=250)),
                ('numero_voie', models.CharField(blank=True, max_length=500)),
                ('lieu_dit', models.CharField(blank=True, max_length=250)),
                ('code_postal', models.CharField(blank=True, max_length=5)),
                ('ville', models.CharField(blank=True, max_length=500)),
                ('pays', models.CharField(blank=True, default='France', max_length=500)),
            ],
        ),
    ]
