# Generated by Django 3.2.19 on 2024-09-24 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0001_initial'),
        ('ouvrage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepriseOuvrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entreprise.entreprise')),
                ('ouvrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouvrage.ouvrage')),
            ],
        ),
    ]
