# Generated by Django 3.2.19 on 2024-08-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionactive',
            name='id_mission',
        ),
        migrations.AddField(
            model_name='missionactive',
            name='id_mission',
            field=models.ManyToManyField(to='mission.Mission'),
        ),
    ]
