# Generated by Django 3.2.19 on 2024-08-31 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0002_initial'),
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionactive',
            name='id_affaire',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Dashbord.affaire'),
        ),
        migrations.AddField(
            model_name='missionactive',
            name='id_mission',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mission.mission'),
        ),
    ]
