# Generated by Django 3.2.19 on 2024-08-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_auto_20240818_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
