# Generated by Django 3.2.19 on 2024-08-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_auto_20240831_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='is_active',
        ),
        migrations.AddField(
            model_name='missionactive',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
