# Generated by Django 3.2.19 on 2024-09-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0003_auto_20240831_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='libelle',
            field=models.CharField(max_length=500),
        ),
    ]
