# Generated by Django 3.2.19 on 2024-10-21 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrage', '0002_entrepriseouvrage'),
        ('mission', '0004_alter_mission_libelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventiontechnique',
            name='libelle',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='DocumentAffectationIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InterventionTechnique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.interventiontechnique')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouvrage.documents')),
            ],
        ),
    ]
