# Generated by Django 3.2.19 on 2024-08-12 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ouvrage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.CharField(max_length=200)),
                ('a_suivre', models.BooleanField(default=True)),
                ('lever', models.BooleanField(default=False)),
                ('id_avis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ouvrage.avis')),
            ],
        ),
    ]
